### ISSUE TITLE
Examples can't run correctly

### ISSUE THREAD

**Issue by Dknightsure** [unadlib/iflow#7]
Hey,

I found some problems when I run the examples that used iflow in your source code.

Maybe your wepack config files in example dir need to make some changes.

```
module.exports = {
  entry: ['babel-polyfill', './index.js'],
  output: {
    filename: "bundle.js",
  },
  module: {
    loaders: [
      {
        test: /\.js|\.jsx/,
        exclude: /node_modules/,
        loader: "babel-loader",
      }
    ]
  },
};
```

Nice library.
Happy to communicate with you, good day.

**Comment by unadlib** [comment]
Thank you for your feedback, can you tell me your execution environment and error log? My new local environment seems to be fine. I hope you like iFlow.

**Comment by Dknightsure** [comment]
node 8.1.4
npm 5.5.1
